networks:
  dev:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: systock-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - dev
    depends_on:
      - systock-db
  
  systock-db:
    container_name: systock-db
    build:
      dockerfile: Dockerfile.db
    ports:
      - "5464:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data:
